services:
  - type: web
    name: portfolio
    runtime: node
    plan: free
    nodeVersion: "22"
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: VITE_SITE_URL
        value: "https://dev-portfolio-clkk.onrender.com"
